wandb_version: 1

learning_rate:
  desc: null
  value: 3.0000000000000004e-05
scheduling:
  desc: null
  value: plateau
lr_factor:
  desc: null
  value: 0.1
lr_patience:
  desc: null
  value: 10
threshold:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: Transformer
epochs:
  desc: null
  value: 100000000
optimizer:
  desc: null
  value: AdamW
max_group_size:
  desc: null
  value: 16
dataset_size:
  desc: null
  value: 100000
input_length:
  desc: null
  value: 100
n_embed:
  desc: null
  value: 24
n_head:
  desc: null
  value: 6
n_blocks:
  desc: null
  value: 12
dropout:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.01
base:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 64
context_length:
  desc: null
  value: 118
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1716729453.360026
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 2
      - 4
      - 6
      13: darwin-arm64
